#!/bin/bash
echo Tools/NugetCopier/Scar.NugetCopier.exe .
Tools/NugetCopier/Scar.NugetCopier.exe .

#sync added files only in Nuget folder (for some reason it doesn't work with -u)
git add Nuget/*

#sync deleted files
git add -u .